### ISSUE TITLE
Create a New Member checklist

### ISSUE THREAD

**Issue by anotherpatrickcollins** [codefordenver/members#312]
"For the new member checklist, maybe it can actually look like a checklist that is concise and inviting on the members site"

idea from Michelle L

**Comment by anotherpatrickcollins** [comment]
Got started on this, I think it should stay short, to be in line with Michelle's vision. 

After onboarding I think all new members should be able to check this list off:

- [ ] Access to your Members Profile
- [ ] Access to Flowdock
- [ ] Access to Github
- [ ] Know where to research projects
- [ ] Know who to contact with questions
- [ ] Know about the next event

Welcome to any additions or edits.
